### PR TITLE
helixer tries to write to home

### PR DESCRIPTION
**Pull request by TomHarrop**
It looks like helixer tries to write to $HOME, can I set it like this? Or should I add a `docker_volumes` ?

```
Traceback (most recent call last):
  File "/usr/local/bin/fetch_helixer_models.py", line 32, in <module>
    main(args.lineage, best_only=not args.all)
  File "/usr/local/bin/fetch_helixer_models.py", line 21, in main
    fetch_and_organize_models(models)
  File "/usr/local/lib/python3.8/dist-packages/helixer/core/data.py", line 22, in fetch_and_organize_models
    os.makedirs(model_path)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/mnt/pulsar/files/staging/7989114/home/.local'
```

### CODE REVIEW

**Comment by neoformit** [comment]
Hmm I guess overwriting `$HOME` could work - I was hoping that the tool would accept an env var or param to set this directly. Hopefully nothing else in this shell depends on `$HOME`?

**Comment by neoformit** [comment]
At what point do you expect `$working_directory` to be resolved here? By TPV or Cheetah?

**Comment by cat-bro** [comment]
I think working_directory is ../staging/1234567/working.  job_directory would be ../staging/1234567 but I don't think it would be substituted - that substitution would probably take place in the docker_volumes/singularity_volumes string only.

You could alter the docker volumes here: https://github.com/usegalaxy-au/infrastructure/blob/master/files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2#L278 and change the 'require' tag on helixir from pulsar-azure-gpu to pulsar-azure-1-gpu.

**Comment by TomHarrop** [comment]
TPV I was hoping.

Helixer writes to `appdirs.user_data_dir` (https://github.com/weberlab-hhu/Helixer/blob/b73c58df2a68b019aa6cf03617e5d76b2102a18c/helixer/core/data.py#L11) which I think is `~/.local`

**Comment by TomHarrop** [comment]
@cat-bro so are (either or both) working or job directory read only by default?

**Comment by cat-bro** [comment]
by docker_volumes we have set. These are the docker_volumes alphafold jobs have: https://github.com/usegalaxy-au/infrastructure/blob/master/files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2#L260

**Comment by cat-bro** [comment]
the way that destinations are set up, they cannot be altered at the tool level. This is tech debt.

**Review by cat-bro — APPROVED** [review]

**Comment by TomHarrop** [comment]
Ah got it! thanks for explaining

**Pull request merged**
