### PR TITLE
Rebrand with themes

### PR DESCRIPTION
**Pull request by neoformit**
- Change main masthead to original Galaxy Europe blue #243e8f
- Use themes to control Galaxy labs styling

### CODE REVIEW

**Review by cat-bro — APPROVED** [review]
LGTM!

**Comment by cat-bro** [comment]
needs this to exist: {{ galaxy_config_file_src_dir }}/config/themes

Could be added to galaxy_extra_dirs (or galaxy_extra_privsep_dirs, whichever one we add mail in) in galaxyservers.yml

**Comment by neoformit** [comment]
I think there is also more lab styling I can move to themes from host vars

**Comment by neoformit** [comment]
Of course, this doesn't work for switching subdomains because of https://github.com/galaxyproject/galaxy/issues/17664
I will revert to specifying CSS in host vars "subsites" conf...

**Comment by neoformit** [comment]
Ok I've tested this on dev and happy to merge now

**Comment by neoformit** [comment]
@cat-bro bump

**Comment by cat-bro** [comment]
sorry I missed this bump. Could the themes.yml go within {{ galaxy_config_dir }}/themes on the galaxy VM? Otherwise looks good to me

**Comment by neoformit** [comment]
Sure!

**Review by cat-bro — APPROVED** [review]

**Comment by cat-bro** [comment]
Thanks @neoformit !

**Pull request merged**
