### PR TITLE
toolmsg webhook plugin on dev + prod

### PR DESCRIPTION
**Pull request by neoformit**
I wrote a webhook plugin that allows us to define tool-specific messages. 

Just [deployed on dev](https://dev.gvl.org.au/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fabyss%2Fabyss-pe%2F2.3.4) last night.

This config in `dev.gvl.org.au.yml`:

```yml
# N.B. make tool_id as short as possible to match all versions
# A trailing slash can result in a mismatch, depending on how the user navigates to the tool form!
toolmsg_messages:
  - tool_id: toolshed.g2.bx.psu.edu/repos/iuc/abyss/abyss-pe
    message: A custom message for ABySS!
    class: danger
```

Results in:

image

The `toolmsg_messages` schema:

```yml
  - tool_id: message will display if current_tool_id.startsWith(tool_id)
    message: A custom message to be displayed for this tool (text only, no HTML currently)
    class: bootstrap class - must be one of [primary, info, success, warning, danger]
```

### CODE REVIEW

**Review by cat-bro — APPROVED** [review]

**Comment by neoformit** [comment]
Please note @cat-bro I pushed another commit to this for prod deployment requested by Gareth.

**Comment by cat-bro** [comment]
This looks great! Could you please alter the console.log statements so that they are always prepended by something like `[toolmsg-webhook] ` or `toolmsg webhook: ` so that it is easy to identify where they are coming from in the console?

**Review by cat-bro — APPROVED** [review]
LGTM!

**Comment by bgruening** [comment]
THIS IS AWESOME!!!!

**Pull request merged**
