### PR TITLE
Set galaxy log level to DEBUG

### PR DESCRIPTION
**Pull request by cat-bro**
The log level is currently at the highest level, TRACE. DEBUG is the default level. Options are (WARN, INFO, DEBUG, TRACE)

### CODE REVIEW

**Comment by cat-bro** [comment]
I don't know if this will make a difference. I can't see TRACE level messages in the logs at all. Lots of DEBUG and INFO

**Comment by nuwang** [comment]
Yes, I don't think there are many TRACE level messages. Do you want to try temporarily setting it to INFO and measuring impact? Also, checking whether logs at INFO level are good enough is also a useful data point.

**Review by nuwang — COMMENTED** [review]
Yes, I don't think there are many TRACE level messages. Do you want to try temporarily setting it to INFO and measuring impact? Also, checking whether logs at INFO level are good enough is also a useful data point.

**Comment by cat-bro** [comment]
This doesn't seem important now, am closing it.

**Pull request closed without merging**
