### PR TITLE
Pulsar qld gpu inventory updates and terraform definitions for VMs

### PR DESCRIPTION
**Pull request by jlqfab**

### CODE REVIEW

**Comment by cat-bro** [comment]
We like to add the backends.tf so that the state file is uploaded and anyone can access it

**Comment by jlqfab** [comment]
backend `swift` was removed in Terraform v1.3, and I've been using v1.8.5.

**Comment by jlqfab** [comment]
apparently Openstack users are recommended to use a postgres backend hosted through a Trove instance. See https://lists.openstack.org/pipermail/openstack-discuss/2022-August/030043.html and https://docs.openstack.org/trove/latest/

**Comment by cat-bro** [comment]
I'll merge it as is. It's tech debt to have no saved state, can you please make an issue for this?

**Review by cat-bro — APPROVED** [review]

**Pull request merged**
