### PR TITLE
Add alphafold test tool

### PR DESCRIPTION
**Pull request by neoformit**
Add `alphafold_test` tool for `v2.3.2` development. The `test` label should hide it from public users right?

```xml
<tool file="/mnt/galaxy/local_tools/alphafold/alphafold.xml" labels="test"/>
```

### CODE REVIEW

**Comment by cat-bro** [comment]
yes, the test label will hide it. This is failing lint. Check for a duplicate key of 'alphafold_test'

**Comment by neoformit** [comment]
Thanks @cat-bro I've removed the duplicate

**Comment by cat-bro** [comment]
the alphafold_db context variable will needs to be added to docker run extra args for that entry

**Comment by neoformit** [comment]
Sorry, I think I was half-asleep on this one

**Review by cat-bro — APPROVED** [review]

**Pull request merged**
